/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseNotificationWidget: typeof import('./src/components/BaseNotificationWidget.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EmergencyNotificationWidget: typeof import('./src/components/EmergencyNotificationWidget.vue')['default']
    HeaderNavigation: typeof import('./src/components/HeaderNavigation.vue')['default']
    ImportantNotificationWidget: typeof import('./src/components/ImportantNotificationWidget.vue')['default']
    NotificationArchiveIndicator: typeof import('./src/components/notification/NotificationArchiveIndicator.vue')['default']
    NotificationArchivePanel: typeof import('./src/components/notification/NotificationArchivePanel.vue')['default']
    PermissionCacheDemo: typeof import('./src/components/PermissionCacheDemo.vue')['default']
    PriorityTestComponent: typeof import('./src/components/PriorityTestComponent.vue')['default']
    QuickServicesGrid: typeof import('./src/components/QuickServicesGrid.vue')['default']
    RegularNotificationWidget: typeof import('./src/components/RegularNotificationWidget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TodoNotificationContainer: typeof import('./src/components/todo/TodoNotificationContainer.vue')['default']
    TodoNotificationItem: typeof import('./src/components/TodoNotificationItem.vue')['default']
    TodoNotificationWidget: typeof import('./src/components/TodoNotificationWidget.vue')['default']
    WeatherWidget: typeof import('./src/components/WeatherWidget.vue')['default']
    WelcomeBanner: typeof import('./src/components/WelcomeBanner.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
